-- phpMyAdmin SQL Dump
-- version 4.4.10
-- http://www.phpmyadmin.net
--
-- Client :  localhost:8889
-- Généré le :  Mar 29 Novembre 2016 à 13:06
-- Version du serveur :  5.5.42
-- Version de PHP :  5.6.10

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Base de données :  `biennale_db`
--

-- --------------------------------------------------------

--
-- Structure de la table `selection`
--

CREATE TABLE `selection` (
  `id` int(2) DEFAULT NULL,
  `num_ecole` int(1) DEFAULT NULL,
  `cygle_ecole` varchar(5) DEFAULT NULL,
  `nom_ecole` varchar(62) DEFAULT NULL,
  `num_livre` int(1) DEFAULT NULL,
  `titre` varchar(13) DEFAULT NULL,
  `auteur` varchar(14) DEFAULT NULL,
  `design` varchar(14) DEFAULT NULL,
  `description` varchar(362) DEFAULT NULL,
  `height` int(3) DEFAULT NULL,
  `width` int(3) DEFAULT NULL,
  `access` varchar(25) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

--
-- Contenu de la table `selection`
--

INSERT INTO `selection` (`id`, `num_ecole`, `cygle_ecole`, `nom_ecole`, `num_livre`, `titre`, `auteur`, `design`, `description`, `height`, `width`, `access`) VALUES
(1, 1, 'UQAM', 'Université du Québec à Montréal', 1, 'Titre Livre 1', 'Auteur Livre 1', 'Design Livre 1', 'You know I can be found, sitting home all alone. If you can''t come around, at least please telephone. Don''t be cruel to a heart that''s true. Baby, if I made you mad for something I might have said, please, let''s forget the past, the future looks bright ahead. Don''t be cruel to a heart that''s true. I don''t want no other love, baby it''s just you I''m thinking of.', 200, 160, 'img/selection/montreal/'),
(2, 1, 'UQAM', 'Université du Québec à Montréal', 2, 'Titre Livre 2', 'Auteur Livre 2', 'Design Livre 2', 'You know I can be found, sitting home all alone. If you can''t come around, at least please telephone. Don''t be cruel to a heart that''s true. Baby, if I made you mad for something I might have said, please, let''s forget the past, the future looks bright ahead. Don''t be cruel to a heart that''s true. I don''t want no other love, baby it''s just you I''m thinking of.', 260, 180, 'img/selection/montreal/'),
(3, 1, 'UQAM', 'Université du Québec à Montréal', 3, 'Titre Livre 3', 'Auteur Livre 3', 'Design Livre 3', 'You know I can be found, sitting home all alone. If you can''t come around, at least please telephone. Don''t be cruel to a heart that''s true. Baby, if I made you mad for something I might have said, please, let''s forget the past, the future looks bright ahead. Don''t be cruel to a heart that''s true. I don''t want no other love, baby it''s just you I''m thinking of.', 275, 225, 'img/selection/montreal/'),
(4, 1, 'UQAM', 'Université du Québec à Montréal', 4, 'Titre Livre 4', 'Auteur Livre 4', 'Design Livre 4', 'You know I can be found, sitting home all alone. If you can''t come around, at least please telephone. Don''t be cruel to a heart that''s true. Baby, if I made you mad for something I might have said, please, let''s forget the past, the future looks bright ahead. Don''t be cruel to a heart that''s true. I don''t want no other love, baby it''s just you I''m thinking of.', 300, 250, 'img/selection/montreal/'),
(5, 1, 'UQAM', 'Université du Québec à Montréal', 5, 'Titre Livre 5', 'Auteur Livre 5', 'Design Livre 5', 'You know I can be found, sitting home all alone. If you can''t come around, at least please telephone. Don''t be cruel to a heart that''s true. Baby, if I made you mad for something I might have said, please, let''s forget the past, the future looks bright ahead. Don''t be cruel to a heart that''s true. I don''t want no other love, baby it''s just you I''m thinking of.', 220, 160, 'img/selection/montreal/'),
(6, 1, 'UQAM', 'Université du Québec à Montréal', 6, 'Titre Livre 6', 'Auteur Livre 6', 'Design Livre 6', 'You know I can be found, sitting home all alone. If you can''t come around, at least please telephone. Don''t be cruel to a heart that''s true. Baby, if I made you mad for something I might have said, please, let''s forget the past, the future looks bright ahead. Don''t be cruel to a heart that''s true. I don''t want no other love, baby it''s just you I''m thinking of.', 265, 100, 'img/selection/montreal/'),
(7, 2, 'EESAB', 'École européenne supérieure d’art de Bretagne - site de Rennes', 1, 'Titre Livre 1', 'Auteur Livre 1', 'Design Livre 1', 'You know I can be found, sitting home all alone. If you can''t come around, at least please telephone. Don''t be cruel to a heart that''s true. Baby, if I made you mad for something I might have said, please, let''s forget the past, the future looks bright ahead. Don''t be cruel to a heart that''s true. I don''t want no other love, baby it''s just you I''m thinking of.', 120, 80, 'img/selection/rennes/'),
(8, 2, 'EESAB', 'École européenne supérieure d’art de Bretagne - site de Rennes', 2, 'Titre Livre 2', 'Auteur Livre 2', 'Design Livre 2', 'You know I can be found, sitting home all alone. If you can''t come around, at least please telephone. Don''t be cruel to a heart that''s true. Baby, if I made you mad for something I might have said, please, let''s forget the past, the future looks bright ahead. Don''t be cruel to a heart that''s true. I don''t want no other love, baby it''s just you I''m thinking of.', 255, 198, 'img/selection/rennes/'),
(9, 2, 'EESAB', 'École européenne supérieure d’art de Bretagne - site de Rennes', 3, 'Titre Livre 3', 'Auteur Livre 3', 'Design Livre 3', 'You know I can be found, sitting home all alone. If you can''t come around, at least please telephone. Don''t be cruel to a heart that''s true. Baby, if I made you mad for something I might have said, please, let''s forget the past, the future looks bright ahead. Don''t be cruel to a heart that''s true. I don''t want no other love, baby it''s just you I''m thinking of.', 220, 130, 'img/selection/rennes/'),
(10, 2, 'EESAB', 'École européenne supérieure d’art de Bretagne - site de Rennes', 4, 'Titre Livre 4', 'Auteur Livre 4', 'Design Livre 4', 'You know I can be found, sitting home all alone. If you can''t come around, at least please telephone. Don''t be cruel to a heart that''s true. Baby, if I made you mad for something I might have said, please, let''s forget the past, the future looks bright ahead. Don''t be cruel to a heart that''s true. I don''t want no other love, baby it''s just you I''m thinking of.', 340, 120, 'img/selection/rennes/'),
(11, 2, 'EESAB', 'École européenne supérieure d’art de Bretagne - site de Rennes', 5, 'Titre Livre 5', 'Auteur Livre 5', 'Design Livre 5', 'You know I can be found, sitting home all alone. If you can''t come around, at least please telephone. Don''t be cruel to a heart that''s true. Baby, if I made you mad for something I might have said, please, let''s forget the past, the future looks bright ahead. Don''t be cruel to a heart that''s true. I don''t want no other love, baby it''s just you I''m thinking of.', 268, 145, 'img/selection/rennes/'),
(12, 2, 'EESAB', 'École européenne supérieure d’art de Bretagne - site de Rennes', 6, 'Titre Livre 6', 'Auteur Livre 6', 'Design Livre 6', 'You know I can be found, sitting home all alone. If you can''t come around, at least please telephone. Don''t be cruel to a heart that''s true. Baby, if I made you mad for something I might have said, please, let''s forget the past, the future looks bright ahead. Don''t be cruel to a heart that''s true. I don''t want no other love, baby it''s just you I''m thinking of.', 230, 100, 'img/selection/rennes/'),
(13, 3, 'ENSBA', 'École nationale supérieure des beaux-arts de Lyon', 1, 'Titre Livre 1', 'Auteur Livre 1', 'Design Livre 1', 'You know I can be found, sitting home all alone. If you can''t come around, at least please telephone. Don''t be cruel to a heart that''s true. Baby, if I made you mad for something I might have said, please, let''s forget the past, the future looks bright ahead. Don''t be cruel to a heart that''s true. I don''t want no other love, baby it''s just you I''m thinking of.', 250, 200, 'img/selection/lyon/'),
(14, 3, 'ENSBA', 'École nationale supérieure des beaux-arts de Lyon', 2, 'Titre Livre 2', 'Auteur Livre 2', 'Design Livre 2', 'You know I can be found, sitting home all alone. If you can''t come around, at least please telephone. Don''t be cruel to a heart that''s true. Baby, if I made you mad for something I might have said, please, let''s forget the past, the future looks bright ahead. Don''t be cruel to a heart that''s true. I don''t want no other love, baby it''s just you I''m thinking of.', 186, 142, 'img/selection/lyon/'),
(15, 3, 'ENSBA', 'École nationale supérieure des beaux-arts de Lyon', 3, 'Titre Livre 3', 'Auteur Livre 3', 'Design Livre 3', 'You know I can be found, sitting home all alone. If you can''t come around, at least please telephone. Don''t be cruel to a heart that''s true. Baby, if I made you mad for something I might have said, please, let''s forget the past, the future looks bright ahead. Don''t be cruel to a heart that''s true. I don''t want no other love, baby it''s just you I''m thinking of.', 285, 240, 'img/selection/lyon/'),
(16, 3, 'ENSBA', 'École nationale supérieure des beaux-arts de Lyon', 4, 'Titre Livre 4', 'Auteur Livre 4', 'Design Livre 4', 'You know I can be found, sitting home all alone. If you can''t come around, at least please telephone. Don''t be cruel to a heart that''s true. Baby, if I made you mad for something I might have said, please, let''s forget the past, the future looks bright ahead. Don''t be cruel to a heart that''s true. I don''t want no other love, baby it''s just you I''m thinking of.', 320, 240, 'img/selection/lyon/'),
(17, 3, 'ENSBA', 'École nationale supérieure des beaux-arts de Lyon', 5, 'Titre Livre 5', 'Auteur Livre 5', 'Design Livre 5', 'You know I can be found, sitting home all alone. If you can''t come around, at least please telephone. Don''t be cruel to a heart that''s true. Baby, if I made you mad for something I might have said, please, let''s forget the past, the future looks bright ahead. Don''t be cruel to a heart that''s true. I don''t want no other love, baby it''s just you I''m thinking of.', 200, 160, 'img/selection/lyon/'),
(18, 3, 'ENSBA', 'École nationale supérieure des beaux-arts de Lyon', 6, 'Titre Livre 6', 'Auteur Livre 6', 'Design Livre 6', 'You know I can be found, sitting home all alone. If you can''t come around, at least please telephone. Don''t be cruel to a heart that''s true. Baby, if I made you mad for something I might have said, please, let''s forget the past, the future looks bright ahead. Don''t be cruel to a heart that''s true. I don''t want no other love, baby it''s just you I''m thinking of.', 180, 140, 'img/selection/lyon/'),
(19, 4, 'ESAD', 'École supérieure d’art et design de Grenoble-Valence', 1, 'Titre Livre 1', 'Auteur Livre 1', 'Design Livre 1', 'You know I can be found, sitting home all alone. If you can''t come around, at least please telephone. Don''t be cruel to a heart that''s true. Baby, if I made you mad for something I might have said, please, let''s forget the past, the future looks bright ahead. Don''t be cruel to a heart that''s true. I don''t want no other love, baby it''s just you I''m thinking of.', 120, 80, 'img/selection/valence/'),
(20, 4, 'ESAD', 'École supérieure d’art et design de Grenoble-Valence', 2, 'Titre Livre 2', 'Auteur Livre 2', 'Design Livre 2', 'You know I can be found, sitting home all alone. If you can''t come around, at least please telephone. Don''t be cruel to a heart that''s true. Baby, if I made you mad for something I might have said, please, let''s forget the past, the future looks bright ahead. Don''t be cruel to a heart that''s true. I don''t want no other love, baby it''s just you I''m thinking of.', 246, 195, 'img/selection/valence/'),
(21, 4, 'ESAD', 'École supérieure d’art et design de Grenoble-Valence', 3, 'Titre Livre 3', 'Auteur Livre 3', 'Design Livre 3', 'You know I can be found, sitting home all alone. If you can''t come around, at least please telephone. Don''t be cruel to a heart that''s true. Baby, if I made you mad for something I might have said, please, let''s forget the past, the future looks bright ahead. Don''t be cruel to a heart that''s true. I don''t want no other love, baby it''s just you I''m thinking of.', 295, 215, 'img/selection/valence/'),
(22, 4, 'ESAD', 'École supérieure d’art et design de Grenoble-Valence', 4, 'Titre Livre 4', 'Auteur Livre 4', 'Design Livre 4', 'You know I can be found, sitting home all alone. If you can''t come around, at least please telephone. Don''t be cruel to a heart that''s true. Baby, if I made you mad for something I might have said, please, let''s forget the past, the future looks bright ahead. Don''t be cruel to a heart that''s true. I don''t want no other love, baby it''s just you I''m thinking of.', 230, 162, 'img/selection/valence/'),
(23, 4, 'ESAD', 'École supérieure d’art et design de Grenoble-Valence', 5, 'Titre Livre 5', 'Auteur Livre 5', 'Design Livre 5', 'You know I can be found, sitting home all alone. If you can''t come around, at least please telephone. Don''t be cruel to a heart that''s true. Baby, if I made you mad for something I might have said, please, let''s forget the past, the future looks bright ahead. Don''t be cruel to a heart that''s true. I don''t want no other love, baby it''s just you I''m thinking of.', 160, 100, 'img/selection/valence/'),
(24, 4, 'ESAD', 'École supérieure d’art et design de Grenoble-Valence', 6, 'Titre Livre 6', 'Auteur Livre 6', 'Design Livre 6', 'You know I can be found, sitting home all alone. If you can''t come around, at least please telephone. Don''t be cruel to a heart that''s true. Baby, if I made you mad for something I might have said, please, let''s forget the past, the future looks bright ahead. Don''t be cruel to a heart that''s true. I don''t want no other love, baby it''s just you I''m thinking of.', 250, 210, 'img/selection/valence/'),
(25, 5, 'HEAR', 'Haute école des arts du Rhin de Strasbourg', 1, 'Titre Livre 1', 'Auteur Livre 1', 'Design Livre 1', 'You know I can be found, sitting home all alone. If you can''t come around, at least please telephone. Don''t be cruel to a heart that''s true. Baby, if I made you mad for something I might have said, please, let''s forget the past, the future looks bright ahead. Don''t be cruel to a heart that''s true. I don''t want no other love, baby it''s just you I''m thinking of.', 240, 120, 'img/selection/strasbourg/'),
(26, 5, 'HEAR', 'Haute école des arts du Rhin de Strasbourg', 2, 'Titre Livre 2', 'Auteur Livre 2', 'Design Livre 2', 'You know I can be found, sitting home all alone. If you can''t come around, at least please telephone. Don''t be cruel to a heart that''s true. Baby, if I made you mad for something I might have said, please, let''s forget the past, the future looks bright ahead. Don''t be cruel to a heart that''s true. I don''t want no other love, baby it''s just you I''m thinking of.', 180, 100, 'img/selection/strasbourg/'),
(27, 5, 'HEAR', 'Haute école des arts du Rhin de Strasbourg', 3, 'Titre Livre 3', 'Auteur Livre 3', 'Design Livre 3', 'You know I can be found, sitting home all alone. If you can''t come around, at least please telephone. Don''t be cruel to a heart that''s true. Baby, if I made you mad for something I might have said, please, let''s forget the past, the future looks bright ahead. Don''t be cruel to a heart that''s true. I don''t want no other love, baby it''s just you I''m thinking of.', 285, 145, 'img/selection/strasbourg/'),
(28, 5, 'HEAR', 'Haute école des arts du Rhin de Strasbourg', 4, 'Titre Livre 4', 'Auteur Livre 4', 'Design Livre 4', 'You know I can be found, sitting home all alone. If you can''t come around, at least please telephone. Don''t be cruel to a heart that''s true. Baby, if I made you mad for something I might have said, please, let''s forget the past, the future looks bright ahead. Don''t be cruel to a heart that''s true. I don''t want no other love, baby it''s just you I''m thinking of.', 160, 220, 'img/selection/strasbourg/'),
(29, 5, 'HEAR', 'Haute école des arts du Rhin de Strasbourg', 5, 'Titre Livre 5', 'Auteur Livre 5', 'Design Livre 5', 'You know I can be found, sitting home all alone. If you can''t come around, at least please telephone. Don''t be cruel to a heart that''s true. Baby, if I made you mad for something I might have said, please, let''s forget the past, the future looks bright ahead. Don''t be cruel to a heart that''s true. I don''t want no other love, baby it''s just you I''m thinking of.', 140, 90, 'img/selection/strasbourg/'),
(30, 5, 'HEAR', 'Haute école des arts du Rhin de Strasbourg', 6, 'Titre Livre 6', 'Auteur Livre 6', 'Design Livre 6', 'You know I can be found, sitting home all alone. If you can''t come around, at least please telephone. Don''t be cruel to a heart that''s true. Baby, if I made you mad for something I might have said, please, let''s forget the past, the future looks bright ahead. Don''t be cruel to a heart that''s true. I don''t want no other love, baby it''s just you I''m thinking of.', 294, 160, 'img/selection/strasbourg/'),
(31, 6, 'ERG', 'École de Recherche Graphique', 1, 'Titre Livre 1', 'Auteur Livre 1', 'Design Livre 1', 'You know I can be found, sitting home all alone. If you can''t come around, at least please telephone. Don''t be cruel to a heart that''s true. Baby, if I made you mad for something I might have said, please, let''s forget the past, the future looks bright ahead. Don''t be cruel to a heart that''s true. I don''t want no other love, baby it''s just you I''m thinking of.', 160, 120, 'img/selection/bruxelles/'),
(32, 6, 'ERG', 'École de Recherche Graphique', 2, 'Titre Livre 2', 'Auteur Livre 2', 'Design Livre 2', 'You know I can be found, sitting home all alone. If you can''t come around, at least please telephone. Don''t be cruel to a heart that''s true. Baby, if I made you mad for something I might have said, please, let''s forget the past, the future looks bright ahead. Don''t be cruel to a heart that''s true. I don''t want no other love, baby it''s just you I''m thinking of.', 265, 140, 'img/selection/bruxelles/'),
(33, 6, 'ERG', 'École de Recherche Graphique', 3, 'Titre Livre 3', 'Auteur Livre 3', 'Design Livre 3', 'You know I can be found, sitting home all alone. If you can''t come around, at least please telephone. Don''t be cruel to a heart that''s true. Baby, if I made you mad for something I might have said, please, let''s forget the past, the future looks bright ahead. Don''t be cruel to a heart that''s true. I don''t want no other love, baby it''s just you I''m thinking of.', 220, 180, 'img/selection/bruxelles/'),
(34, 6, 'ERG', 'École de Recherche Graphique', 4, 'Titre Livre 4', 'Auteur Livre 4', 'Design Livre 4', 'You know I can be found, sitting home all alone. If you can''t come around, at least please telephone. Don''t be cruel to a heart that''s true. Baby, if I made you mad for something I might have said, please, let''s forget the past, the future looks bright ahead. Don''t be cruel to a heart that''s true. I don''t want no other love, baby it''s just you I''m thinking of.', 280, 220, 'img/selection/bruxelles/'),
(35, 6, 'ERG', 'École de Recherche Graphique', 5, 'Titre Livre 5', 'Auteur Livre 5', 'Design Livre 5', 'You know I can be found, sitting home all alone. If you can''t come around, at least please telephone. Don''t be cruel to a heart that''s true. Baby, if I made you mad for something I might have said, please, let''s forget the past, the future looks bright ahead. Don''t be cruel to a heart that''s true. I don''t want no other love, baby it''s just you I''m thinking of.', 320, 240, 'img/selection/bruxelles/'),
(36, 6, 'ERG', 'École de Recherche Graphique', 6, 'Titre Livre 6', 'Auteur Livre 6', 'Design Livre 6', 'You know I can be found, sitting home all alone. If you can''t come around, at least please telephone. Don''t be cruel to a heart that''s true. Baby, if I made you mad for something I might have said, please, let''s forget the past, the future looks bright ahead. Don''t be cruel to a heart that''s true. I don''t want no other love, baby it''s just you I''m thinking of.', 195, 135, 'img/selection/bruxelles/'),
(37, 7, 'HEAD', 'Haute école d’art et de design de Genève', 1, 'Titre Livre 1', 'Auteur Livre 1', 'Design Livre 1', 'You know I can be found, sitting home all alone. If you can''t come around, at least please telephone. Don''t be cruel to a heart that''s true. Baby, if I made you mad for something I might have said, please, let''s forget the past, the future looks bright ahead. Don''t be cruel to a heart that''s true. I don''t want no other love, baby it''s just you I''m thinking of.', 220, 280, 'img/selection/geneve/'),
(38, 7, 'HEAD', 'Haute école d’art et de design de Genève', 2, 'Titre Livre 2', 'Auteur Livre 2', 'Design Livre 2', 'You know I can be found, sitting home all alone. If you can''t come around, at least please telephone. Don''t be cruel to a heart that''s true. Baby, if I made you mad for something I might have said, please, let''s forget the past, the future looks bright ahead. Don''t be cruel to a heart that''s true. I don''t want no other love, baby it''s just you I''m thinking of.', 270, 145, 'img/selection/geneve/'),
(39, 7, 'HEAD', 'Haute école d’art et de design de Genève', 3, 'Titre Livre 3', 'Auteur Livre 3', 'Design Livre 3', 'You know I can be found, sitting home all alone. If you can''t come around, at least please telephone. Don''t be cruel to a heart that''s true. Baby, if I made you mad for something I might have said, please, let''s forget the past, the future looks bright ahead. Don''t be cruel to a heart that''s true. I don''t want no other love, baby it''s just you I''m thinking of.', 180, 165, 'img/selection/geneve/'),
(40, 7, 'HEAD', 'Haute école d’art et de design de Genève', 4, 'Titre Livre 4', 'Auteur Livre 4', 'Design Livre 4', 'You know I can be found, sitting home all alone. If you can''t come around, at least please telephone. Don''t be cruel to a heart that''s true. Baby, if I made you mad for something I might have said, please, let''s forget the past, the future looks bright ahead. Don''t be cruel to a heart that''s true. I don''t want no other love, baby it''s just you I''m thinking of.', 256, 215, 'img/selection/geneve/'),
(41, 7, 'HEAD', 'Haute école d’art et de design de Genève', 5, 'Titre Livre 5', 'Auteur Livre 5', 'Design Livre 5', 'You know I can be found, sitting home all alone. If you can''t come around, at least please telephone. Don''t be cruel to a heart that''s true. Baby, if I made you mad for something I might have said, please, let''s forget the past, the future looks bright ahead. Don''t be cruel to a heart that''s true. I don''t want no other love, baby it''s just you I''m thinking of.', 290, 190, 'img/selection/geneve/'),
(42, 7, 'HEAD', 'Haute école d’art et de design de Genève', 6, 'Titre Livre 6', 'Auteur Livre 6', 'Design Livre 6', 'You know I can be found, sitting home all alone. If you can''t come around, at least please telephone. Don''t be cruel to a heart that''s true. Baby, if I made you mad for something I might have said, please, let''s forget the past, the future looks bright ahead. Don''t be cruel to a heart that''s true. I don''t want no other love, baby it''s just you I''m thinking of.', 210, 145, 'img/selection/geneve/'),
(43, 8, 'ISDAT', 'Institut supérieur des arts de Toulouse', 1, 'Titre Livre 1', 'Auteur Livre 1', 'Design Livre 1', 'You know I can be found, sitting home all alone. If you can''t come around, at least please telephone. Don''t be cruel to a heart that''s true. Baby, if I made you mad for something I might have said, please, let''s forget the past, the future looks bright ahead. Don''t be cruel to a heart that''s true. I don''t want no other love, baby it''s just you I''m thinking of.', 300, 200, 'img/selection/toulouse/'),
(44, 8, 'ISDAT', 'Institut supérieur des arts de Toulouse', 2, 'Titre Livre 2', 'Auteur Livre 2', 'Design Livre 2', 'You know I can be found, sitting home all alone. If you can''t come around, at least please telephone. Don''t be cruel to a heart that''s true. Baby, if I made you mad for something I might have said, please, let''s forget the past, the future looks bright ahead. Don''t be cruel to a heart that''s true. I don''t want no other love, baby it''s just you I''m thinking of.', 160, 90, 'img/selection/toulouse/'),
(45, 8, 'ISDAT', 'Institut supérieur des arts de Toulouse', 3, 'Titre Livre 3', 'Auteur Livre 3', 'Design Livre 3', 'You know I can be found, sitting home all alone. If you can''t come around, at least please telephone. Don''t be cruel to a heart that''s true. Baby, if I made you mad for something I might have said, please, let''s forget the past, the future looks bright ahead. Don''t be cruel to a heart that''s true. I don''t want no other love, baby it''s just you I''m thinking of.', 240, 160, 'img/selection/toulouse/'),
(46, 8, 'ISDAT', 'Institut supérieur des arts de Toulouse', 4, 'Titre Livre 4', 'Auteur Livre 4', 'Design Livre 4', 'You know I can be found, sitting home all alone. If you can''t come around, at least please telephone. Don''t be cruel to a heart that''s true. Baby, if I made you mad for something I might have said, please, let''s forget the past, the future looks bright ahead. Don''t be cruel to a heart that''s true. I don''t want no other love, baby it''s just you I''m thinking of.', 280, 200, 'img/selection/toulouse/'),
(47, 8, 'ISDAT', 'Institut supérieur des arts de Toulouse', 5, 'Titre Livre 5', 'Auteur Livre 5', 'Design Livre 5', 'You know I can be found, sitting home all alone. If you can''t come around, at least please telephone. Don''t be cruel to a heart that''s true. Baby, if I made you mad for something I might have said, please, let''s forget the past, the future looks bright ahead. Don''t be cruel to a heart that''s true. I don''t want no other love, baby it''s just you I''m thinking of.', 140, 80, 'img/selection/toulouse/'),
(48, 8, 'ISDAT', 'Institut supérieur des arts de Toulouse', 6, 'Titre Livre 6', 'Auteur Livre 6', 'Design Livre 6', 'You know I can be found, sitting home all alone. If you can''t come around, at least please telephone. Don''t be cruel to a heart that''s true. Baby, if I made you mad for something I might have said, please, let''s forget the past, the future looks bright ahead. Don''t be cruel to a heart that''s true. I don''t want no other love, baby it''s just you I''m thinking of.', 260, 156, 'img/selection/toulouse/'),
(49, 9, 'ISBA', 'Institut supérieur des beaux arts de Besançon', 1, 'Titre Livre 1', 'Auteur Livre 1', 'Design Livre 1', 'You know I can be found, sitting home all alone. If you can''t come around, at least please telephone. Don''t be cruel to a heart that''s true. Baby, if I made you mad for something I might have said, please, let''s forget the past, the future looks bright ahead. Don''t be cruel to a heart that''s true. I don''t want no other love, baby it''s just you I''m thinking of.', 275, 175, 'img/selection/besancon/'),
(50, 9, 'ISBA', 'Institut supérieur des beaux arts de Besançon', 2, 'Titre Livre 2', 'Auteur Livre 2', 'Design Livre 2', 'You know I can be found, sitting home all alone. If you can''t come around, at least please telephone. Don''t be cruel to a heart that''s true. Baby, if I made you mad for something I might have said, please, let''s forget the past, the future looks bright ahead. Don''t be cruel to a heart that''s true. I don''t want no other love, baby it''s just you I''m thinking of.', 320, 240, 'img/selection/besancon/'),
(51, 9, 'ISBA', 'Institut supérieur des beaux arts de Besançon', 3, 'Titre Livre 3', 'Auteur Livre 3', 'Design Livre 3', 'You know I can be found, sitting home all alone. If you can''t come around, at least please telephone. Don''t be cruel to a heart that''s true. Baby, if I made you mad for something I might have said, please, let''s forget the past, the future looks bright ahead. Don''t be cruel to a heart that''s true. I don''t want no other love, baby it''s just you I''m thinking of.', 220, 280, 'img/selection/besancon/'),
(52, 9, 'ISBA', 'Institut supérieur des beaux arts de Besançon', 4, 'Titre Livre 4', 'Auteur Livre 4', 'Design Livre 4', 'You know I can be found, sitting home all alone. If you can''t come around, at least please telephone. Don''t be cruel to a heart that''s true. Baby, if I made you mad for something I might have said, please, let''s forget the past, the future looks bright ahead. Don''t be cruel to a heart that''s true. I don''t want no other love, baby it''s just you I''m thinking of.', 260, 180, 'img/selection/besancon/'),
(53, 9, 'ISBA', 'Institut supérieur des beaux arts de Besançon', 5, 'Titre Livre 5', 'Auteur Livre 5', 'Design Livre 5', 'You know I can be found, sitting home all alone. If you can''t come around, at least please telephone. Don''t be cruel to a heart that''s true. Baby, if I made you mad for something I might have said, please, let''s forget the past, the future looks bright ahead. Don''t be cruel to a heart that''s true. I don''t want no other love, baby it''s just you I''m thinking of.', 190, 135, 'img/selection/besancon/'),
(54, 9, 'ISBA', 'Institut supérieur des beaux arts de Besançon', 6, 'Titre Livre 6', 'Auteur Livre 6', 'Design Livre 6', 'You know I can be found, sitting home all alone. If you can''t come around, at least please telephone. Don''t be cruel to a heart that''s true. Baby, if I made you mad for something I might have said, please, let''s forget the past, the future looks bright ahead. Don''t be cruel to a heart that''s true. I don''t want no other love, baby it''s just you I''m thinking of.', 225, 120, 'img/selection/besancon/');

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
