title: Site

pages:
  template:
    - default
    - selection

fields:
  title:
    label: Title
    type:  text

  author:
    label: Author
    type:  text

  description:
    label: Description
    type:  textarea
    
  copyright:
    label: Copyright
    type:  textarea

  maintenance:
    label: Maintenance
    type: checkbox
    text: Enable Maintenance
